#!/bin/sh
#
# Start linux bootanimation...
#

case "$1" in
  start)
		printf "Starting bootanimation: "
        bootanimation &
	;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
