#!/bin/sh
#
# Start linux bootanimation...
#

case "$1" in
  start)
	printf "Starting bootanimation: "
	#for hdmi and cvbs
	hdmi=$(cat /sys/class/drm/card0-HDMI-A-1/status)
	cvbs=$(cat /sys/class/drm/card0-TV-1/status)

        if [ $hdmi == connected ]; then
             echo off > /sys/class/drm/card0-TV-1/status
             cp /usr/share/alsa/alsa_hdmi.conf /usr/share/alsa/alsa.conf
        elif [ $cvbs == connected ]; then
		echo off > /sys/class/drm/card0-HDMI-A-1/status
	fi
	#for modeset
	/usr/bin/modeset &

        bootanimation &
	;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
