#!/bin/sh
#
# Start rk3326 linux service....
#

case "$1" in
	start)
		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

		# ueventd
		/usr/bin/ueventd &

		sleep 5   #wait for ueventd finish scan and create mount point
		mount -a

		ln -s /dev/block/platform/ff390000.dwmmc/by-name/misc /misc
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

