#!/bin/sh
#
# Insmod
#

case "$1" in
  start)
        printf "insmod vcodec service...\n"
        insmod /usr/lib/modules/vcodec_service.ko
        ;;
  stop)
        printf "kill ueventmonitor\n"
        printf "stop finished\n"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
