#!/bin/sh
#
# Insmod
#

case "$1" in
  start)
        printf "insmod drmboot service...\n"
        insmod /usr/lib/modules/drmboot.ko
        ;;
  stop)
        printf "stop finished\n"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
