#!/bin/sh
#
# Start Rockchip ueventd....
#

case "$1" in
	start)
		/usr/bin/ueventd &
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

