#!/bin/sh
#
# Start make dir....
#

case "$1" in
	start)
		mkdir /data
		mkdir /misc
		mkdir /sdcard
		mkdir /userdata
		mkdir /oem
		mkdir /udisk
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

